title: Raghav Raahul Manoharan Jayanthi
logo: "/pictures/profile.jpg?raw=true"
description: >
  <br>
  <p align="center">
    Master of Business Analytics, MIT
    <br>
    BS, Georgia Institute of Technology
    <br><br>
    <img src="images/linkedin.jpg?raw=true" width="5%" height="5%"/>
    <a href="https://www.linkedin.com/in/rrmj/"></a> 
    <br>
    <img src="images/github.jpg?raw=true" width="5%" height="5%"/>
    <a href="https://github.com/raghavmanoharanjayanthi30/"></a> 
    <br>
    <br>
    <img src="pictures/mit.jpg?raw=true" width="30%" height="30%"/>
    <img src="pictures/gt.jpg?raw=true" width="30%" height="30%"/>
  </p>
  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
