title: Raghav Raahul Manoharan Jayanthi
logo: "/pictures/profile.jpg?raw=true"
description: >
  <p align="center">
    Master of Business Analytics, MIT
    <br>
    BS, Georgia Institute of Technology
    <br><br>
    <img src="pictures/mit.png?raw=true" width="30%" height="30%"/>
    <img src="pictures/gt.png?raw=true" width="30%" height="30%"/>
  </p>
  
  
theme: jekyll-theme-minimal

