title: Raghav Raahul Manoharan Jayanthi
logo: "/pictures/profile.jpg?raw=true"
description: >
  <br>
  <p align="center">
    Master of Business Analytics, MIT
    <br>
    BS, Georgia Institute of Technology
    <br><br>
    <img src="images/linkedin_logo.png?raw=true" width="5%" height="5%"/>
    <a href="https://www.linkedin.com/in/rrmj/">rachit1jain</a> 
    <br>
    <img src="images/github_logo.png?raw=true" width="5%" height="5%"/>
    <a href="https://github.com/raghavmanoharanjayanthi30/"></a> 
    <br>
    <br>
    <img src="https://github.com/rachit-0032/rachit-0032.github.io/blob/master/images/iitd_logo.png?raw=true" width="30%" height="30%"/>
    <img src="https://github.com/rachit-0032/rachit-0032.github.io/blob/master/images/mit_logo.png?raw=true" width="30%" height="30%"/>
  </p>
  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
